adapter: lora
base_model: meta-llama/Llama-3.1-8B-Instruct

datasets:
- path: mariiazhiv/Cybersecurity_messages
  split: train
  type: chat_template
  field_messages: messages
  chat_template: llama3
  
test_datasets:
- path: mariiazhiv/Cybersecurity_messages
  split: validation
  type: chat_template
  field_messages: messages
  chat_template: llama3
    
dataset_prepared_path: last_run_prepared
output_dir: ./outputs/mymodel

sequence_len: 1024

lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - down_proj
  - up_proj

gradient_accumulation_steps: 8
micro_batch_size: 4
num_epochs: 2
optimizer: adamw_bnb_8bit
learning_rate: 0.0001
load_in_8bit: false
train_on_inputs: false
bf16: true
fp16: false
gradient_checkpointing: true

special_tokens:
  pad_token: "<|pad|>"
