base_model: meta-llama/Llama-2-13b-chat-hf
datasets:
  - path: mariiazhiv/cybersecurity_qa
    type: alpaca
    split: train
  - path: mariiazhiv/cybersecurity_qa
    type: alpaca
    split: validation
dataset_prepared_path: last_run_prepared
output_dir: ./outputs/mymodel

sequence_len: 1024
adapter: lora

lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - down_proj
  - up_proj

gradient_accumulation_steps: 8
micro_batch_size: 4
num_epochs: 1
max_steps: 300
optimizer: adamw_bnb_8bit
learning_rate: 0.00001
load_in_8bit: false
train_on_inputs: false
bf16: false
fp16: true
gradient_checkpointing: true

special_tokens:
  pad_token: "<|pad|>"
